// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyzlwcxwtxmzgiigcsel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5emx3Y3h3dHhtemdpaWdjc2VsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjA1MDEsImV4cCI6MjA2NTUzNjUwMX0.z0TepMs_iBK0I8DG9JLBOUyTK_PBRPd2BtGpMbd8cJc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);